// ─── CalculadoraInversion.tsx ─────────────────────────────────────────────────
// Ruta: /calculadora-de-inversion
// Calculadora de interés compuesto con aportaciones mensuales — SEO 2025
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useEffect } from 'react';
import { TrendingUp } from 'lucide-react';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip,
  Legend, ResponsiveContainer, PieChart, Pie, Cell,
} from 'recharts';
import { useLanguage } from '../../context/LanguageContext';
import { SEO } from '../../components/SEO';
import {
  Currency,
  CurrencyContext,
  CurrencySelector,
  FaqSection,
  Breadcrumb,
  formatResult,
  useFormattedInput,
  useCurrency,
  CURRENCY_MAP,
} from './_shared';

type ContributionTiming = 'beginning' | 'end';

const FAQ_INVERSION = [
  {
    q_es: '¿Qué es el interés compuesto y por qué es clave para tu libertad financiera?',
    q_en: 'What is compound interest and why is it key to your financial freedom?',
    a_es: 'El interés compuesto es el fenómeno financiero donde los rendimientos generados por una inversión inicial se suman al capital principal de forma periódica, permitiendo que en el siguiente periodo los intereses se calculen sobre una base mayor y generen, a su vez, nuevos beneficios en un efecto de bola de nieve ascendente; a diferencia del interés simple, donde la ganancia es lineal y constante, el interés compuesto aprovecha el factor tiempo para producir un crecimiento exponencial de la riqueza, lo que llevó a Albert Einstein a calificarlo como "la octava maravilla del mundo" y la fuerza más poderosa del universo, siendo una herramienta indispensable para cualquier ahorrador o inversor que busque maximizar su patrimonio a largo plazo mediante la reinversión sistemática de dividendos o utilidades, reduciendo la necesidad de grandes aportes de capital gracias a la capitalización continua que ocurre cuando se mantiene la disciplina y el horizonte de inversión adecuado.',
    a_en: 'Compound interest is the financial phenomenon where the returns generated by an initial investment are added to the principal capital on a periodic basis, allowing interest in the following period to be calculated on a larger base and, in turn, generate new profits in a snowball effect; unlike simple interest, where the gain is linear and constant, compound interest leverages the time factor to produce exponential wealth growth, leading Albert Einstein to describe it as "the eighth wonder of the world" and the most powerful force in the universe, being an indispensable tool for any saver or investor seeking to maximize their long-term assets through the systematic reinvestment of dividends or profits, reducing the need for large capital contributions thanks to the continuous capitalization that occurs when discipline and the appropriate investment horizon are maintained.',
  },
  {
    q_es: '¿Cuánto rinde invertir $10,000 en 10 años y cómo maximizar ese resultado?',
    q_en: 'How much does investing $10,000 yield in 10 years and how can I maximize that result?',
    a_es: 'El rendimiento de una inversión de $10,000 en un horizonte de 10 años depende directamente de la tasa de retorno anual y de la frecuencia de capitalización, pero tomando como referencia un rendimiento del 8% anual —promedio histórico cercano al mercado de valores— sin realizar aportaciones adicionales, el capital se transformaría en aproximadamente $21,589 gracias a la magia del interés compuesto que duplica con creces la inversión inicial; sin embargo, este resultado puede potenciarse drásticamente si se añaden contribuciones mensuales, ya que el interés compuesto trabaja de forma más agresiva sobre una base de capital que crece constantemente, por lo que es vital considerar factores como la inflación, que afecta el poder adquisitivo futuro, y las comisiones de gestión de las plataformas de inversión, siendo esta calculadora una herramienta esencial para proyectar escenarios realistas que demuestran cómo la paciencia y la consistencia en el mercado pueden convertir una suma moderada en un patrimonio significativo sin necesidad de asumir riesgos excesivos.',
    a_en: 'The yield of a $10,000 investment over a 10-year horizon depends directly on the annual rate of return and the compounding frequency, but taking an 8% annual return as a reference—a historical average close to the stock market—without making additional contributions, the capital would transform into approximately $21,589 thanks to the magic of compound interest that more than doubles the initial investment; however, this result can be drastically enhanced if monthly contributions are added, as compound interest works more aggressively on a constantly growing capital base, so it is vital to consider factors such as inflation, which affects future purchasing power, and management fees from investment platforms, making this calculator an essential tool for projecting realistic scenarios that demonstrate how patience and consistency in the market can turn a moderate sum into a significant asset without taking on excessive risks.',
  },
  {
    q_es: '¿Cuál es la diferencia entre anualidad anticipada y vencida?',
    q_en: "What's the difference between annuity due and ordinary annuity in an investment?",
    a_es: 'La distinción fundamental entre una anualidad anticipada y una vencida radica exclusivamente en el momento exacto en que se realiza el flujo de caja dentro de cada periodo de capitalización, siendo la anualidad anticipada aquella donde los pagos o aportes se efectúan al inicio de cada mes o año, permitiendo que ese capital comience a devengar intereses desde el primer día, mientras que en la anualidad vencida u ordinaria el aporte se deposita al final del periodo; aunque la diferencia pueda parecer sutil en el corto plazo, en inversiones de largo horizonte el uso de anualidades anticipadas genera un resultado final acumulado mayor, ya que cada depósito cuenta con un periodo adicional de capitalización de intereses, por lo que es un factor determinante al calcular planes de jubilación, fondos de ahorro para la educación o el pago de primas de seguros, donde entender esta sutil ventaja matemática permite al inversor optimizar el crecimiento de su patrimonio mediante una planificación temporal más eficiente.',
    a_en: 'The fundamental distinction between an annuity due and an ordinary annuity lies exclusively in the exact timing of the cash flow within each compounding period, with an annuity due being one where payments or contributions are made at the beginning of each month or year, allowing that capital to begin earning interest from day one, whereas in an ordinary annuity, the contribution is deposited at the end of the period; although the difference may seem subtle in the short term, in long-horizon investments, the use of annuities due generates a higher final accumulated result, as each deposit benefits from an additional interest compounding period, making it a determining factor when calculating retirement plans, education savings funds, or insurance premium payments, where understanding this subtle mathematical advantage allows the investor to optimize wealth growth through more efficient timing and planning.',
  },
  {
    q_es: '¿Cuánto debo invertir mensualmente para ser millonario y cómo afecta el tiempo al resultado?',
    q_en: 'How much should I invest monthly to become a millionaire and how does time affect the outcome?',
    a_es: 'Alcanzar el estatus de millonario es un objetivo numérico que depende de la interacción entre tres variables críticas: el capital mensual aportado, la tasa de rendimiento anual y, fundamentalmente, el horizonte temporal de la inversión; por ejemplo, bajo un escenario conservador de mercado con un rendimiento del 8% anual, una persona que comienza con disciplina a los 30 años de edad necesitaría invertir aproximadamente $671 mensuales para acumular un millón de dólares al momento de su jubilación tres décadas después, sin embargo, si ese mismo objetivo se busca alcanzar en solo 20 años, el esfuerzo de ahorro mensual debe incrementarse drásticamente hasta los $1,698 debido a que se dispone de menos tiempo para que el interés compuesto multiplique el capital; esta diferencia subraya la importancia de comenzar a invertir lo antes posible, ya que el tiempo actúa como un multiplicador de fuerza que reduce la carga del ahorro individual, permitiendo que la mayor parte del patrimonio final provenga de las ganancias reinvertidas y no solo del dinero salido del bolsillo del inversor, convirtiendo la constancia y la paciencia en los activos más valiosos de cualquier estrategia patrimonial.',
    a_en: "Becoming a millionaire is a numerical goal that depends on the interaction of three critical variables: the monthly capital contributed, the annual rate of return, and, fundamentally, the investment time horizon; for instance, under a conservative market scenario with an 8% annual return, a person who starts with discipline at age 30 would need to invest approximately $671 per month to accumulate one million dollars by their retirement three decades later, however, if that same goal is sought in just 20 years, the monthly savings effort must drastically increase to $1,698 because there is less time for compound interest to multiply the capital; this difference underscores the importance of starting to invest as early as possible, as time acts as a force multiplier that reduces the individual savings burden, allowing the bulk of the final wealth to come from reinvested earnings rather than just the money out of the investor's pocket, turning consistency and patience into the most valuable assets of any long-term wealth strategy.",
  },
  {
    q_es: '¿Con qué frecuencia se capitaliza el interés compuesto en esta calculadora y por qué importa?',
    q_en: 'How often does this calculator compound interest and why does it matter?',
    a_es: 'Nuestra calculadora está configurada para utilizar una capitalización mensual por defecto, lo que significa que el ciclo de cálculo y reinversión de utilidades ocurre doce veces al año, reflejando fielmente el funcionamiento de la mayoría de los productos bancarios, fondos de inversión y cuentas de ahorro del mercado real; es fundamental entender que a mayor frecuencia de capitalización —ya sea diaria, mensual o trimestral— más rápido crece el capital total, debido a que los intereses generados comienzan a producir nuevos rendimientos en un periodo de tiempo más corto, lo que genera un "rendimiento efectivo" superior a la tasa nominal anunciada, por lo cual esta herramienta se convierte en un recurso indispensable para proyectar el crecimiento de tu patrimonio con una precisión que se ajusta a la realidad de los estados de cuenta mensuales y a las estrategias de inversión periódicas.',
    a_en: 'Our calculator is configured to use monthly compounding by default, meaning the calculation and reinvestment cycle of earnings occurs twelve times a year, accurately reflecting the operation of most banking products, investment funds, and savings accounts in the real market; it is essential to understand that the higher the compounding frequency—whether daily, monthly, or quarterly—the faster the total capital grows, because the generated interest begins producing new returns in a shorter period, resulting in an "effective yield" higher than the advertised nominal rate, making this tool an indispensable resource for projecting wealth growth with a precision that matches real-world monthly bank statements and periodic investment strategies.',
  },
  {
    q_es: '¿Cómo afecta la inflación al rendimiento real de mi inversión a largo plazo?',
    q_en: 'How does inflation affect the real return of my long-term investment?',
    a_es: 'Ignorar la inflación es uno de los errores más comunes al proyectar inversiones, ya que mientras el interés compuesto hace crecer el número nominal de tu dinero, la inflación reduce el poder adquisitivo de cada unidad monetaria con el paso del tiempo, lo que significa que un millón de dólares en el futuro no comprará los mismos bienes que un millón hoy; por ello, al utilizar esta calculadora, es recomendable restar la tasa de inflación estimada de tu rendimiento esperado para obtener una "tasa de retorno real", permitiéndote planificar objetivos financieros que no solo se vean grandes en papel, sino que mantengan su valor y capacidad de compra en el mundo real, garantizando así una jubilación o un patrimonio verdaderamente sólido y protegido contra la devaluación económica.',
    a_en: 'Ignoring inflation is one of the most common mistakes when projecting investments, as while compound interest increases the nominal amount of your money, inflation reduces the purchasing power of each monetary unit over time, meaning that a million dollars in the future will not buy the same goods as a million today; therefore, when using this calculator, it is recommended to subtract the estimated inflation rate from your expected return to obtain an "real rate of return", allowing you to plan financial goals that are not only large on paper but also maintain their value and buying power in the real world, ensuring a truly solid and protected retirement or wealth accumulation against economic devaluation.',
  },
  {
    q_es: '¿Cuál es la diferencia real de ganancias entre el interés simple y el compuesto?',
    q_en: 'What is the real difference in earnings between simple and compound interest?',
    a_es: 'La diferencia entre el interés simple y el compuesto es la diferencia entre un crecimiento lineal y un crecimiento exponencial, ya que en el interés simple las ganancias se retiran y siempre se calcula sobre el capital original, produciendo un aumento constante pero lento, mientras que en el interés compuesto los beneficios se acumulan para generar sus propios intereses en el siguiente ciclo; matemáticamente, esta diferencia puede representar cientos de miles de dólares en un plazo de 20 o 30 años, convirtiendo una inversión que apenas superaría la inflación en una verdadera fortuna, lo que demuestra que la reinversión de utilidades es el motor más potente para la creación de riqueza y la razón por la cual los inversores más exitosos priorizan la capitalización sobre el retiro inmediato de dividendos.',
    a_en: 'The difference between simple and compound interest is the difference between linear and exponential growth, as with simple interest earnings are withdrawn and always calculated on the original capital, producing a constant but slow increase, while with compound interest benefits accumulate to generate their own interest in the next cycle; mathematically, this difference can represent hundreds of thousands of dollars over a 20 or 30-year period, turning an investment that would barely outpace inflation into a true fortune, demonstrating that reinvesting profits is the most powerful engine for wealth creation and the reason why the most successful investors prioritize compounding over immediate dividend withdrawals.',
  },
];

// ── Componente interno ────────────────────────────────────────────────────────
function CompoundCalculatorInner() {
  const { symbol, currency } = useCurrency();
  const { language } = useLanguage();
  const { value: initialValue, rawValue: initialAmount, handleChange: setInitialAmount } = useFormattedInput('0', false);
  const { value: monthlyValue, rawValue: monthlyAdd,    handleChange: setMonthlyAdd    } = useFormattedInput('0', false);
  const { value: rateValue,    rawValue: rate,          handleChange: setRate          } = useFormattedInput('0', true);
  const { value: yearsValue,   rawValue: years,         handleChange: setYears         } = useFormattedInput('0', false);
  const [contributionTiming, setContributionTiming] = useState<ContributionTiming>('end');
  const [chartData,   setChartData]   = useState<Array<{ year: number; invertido: number; ganancias: number; total: number }>>([]);
  const [annualTable, setAnnualTable] = useState<Array<{ year: number; aportado: number; intereses: number; total: number }>>([]);
  const [result,      setResult]      = useState<{ finalAmount: number; totalInvested: number; totalInterest: number } | null>(null);

  useEffect(() => { calculateCompound(); }, [initialAmount, monthlyAdd, rate, years, contributionTiming]);

  const calculateCompound = () => {
    const P          = initialAmount;
    const PMT        = monthlyAdd;
    const annualRate = rate / 100;
    const yearsCount = years;
    const monthlyRate  = annualRate / 12;
    const totalMonths  = yearsCount * 12;
    const fvPrincipal  = P * Math.pow(1 + monthlyRate, totalMonths);
    let fvContributions = 0;
    if (monthlyRate > 0 && PMT > 0) {
      const annuityFactor = (Math.pow(1 + monthlyRate, totalMonths) - 1) / monthlyRate;
      fvContributions = PMT * annuityFactor;
      if (contributionTiming === 'beginning') fvContributions *= (1 + monthlyRate);
    } else if (PMT > 0) {
      fvContributions = PMT * totalMonths;
    }
    const finalAmount    = fvPrincipal + fvContributions;
    const totalInvested  = P + PMT * totalMonths;
    const totalInterest  = finalAmount - totalInvested;
    const yearlyData:  typeof chartData   = [];
    const yearlyTable: typeof annualTable = [];
    for (let year = 1; year <= yearsCount; year++) {
      const m = year * 12;
      const yFvP = P * Math.pow(1 + monthlyRate, m);
      let yFvC = 0;
      if (monthlyRate > 0 && PMT > 0) {
        const af = (Math.pow(1 + monthlyRate, m) - 1) / monthlyRate;
        yFvC = PMT * af;
        if (contributionTiming === 'beginning') yFvC *= (1 + monthlyRate);
      } else if (PMT > 0) {
        yFvC = PMT * m;
      }
      const yTotal    = yFvP + yFvC;
      const yInvested = P + PMT * m;
      yearlyData.push({ year, invertido: yInvested, ganancias: Math.max(0, yTotal - yInvested), total: yTotal });
      yearlyTable.push({ year, aportado: yInvested, intereses: Math.max(0, yTotal - yInvested), total: yTotal });
    }
    setChartData(yearlyData);
    setAnnualTable(yearlyTable);
    setResult({ finalAmount, totalInvested, totalInterest });
  };

  const tooltipFormatter = (value: any): [string, string] => {
    if (value == null) return ['', ''];
    const num = typeof value === 'string' ? parseFloat(value) : Number(value);
    return [`${symbol}${formatResult(num, currency)}`, ''];
  };

  return (
    <div className="max-w-5xl mx-auto">
      {/* Inputs */}
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
        {[
          { id: 'ci-initial', label: language === 'es' ? 'Monto Inicial' : 'Initial Amount',           value: initialValue, onChange: setInitialAmount, placeholder: '10.000', decimal: false },
          { id: 'ci-monthly', label: language === 'es' ? 'Aportación Mensual' : 'Monthly Contribution', value: monthlyValue, onChange: setMonthlyAdd,    placeholder: '500',    decimal: false },
          { id: 'ci-rate',    label: language === 'es' ? 'Rendimiento Anual (%)' : 'Annual Return (%)', value: rateValue,    onChange: setRate,          placeholder: '8',      decimal: true  },
          { id: 'ci-years',   label: language === 'es' ? 'Años de inversión' : 'Investment Years',      value: yearsValue,   onChange: setYears,         placeholder: '10',     decimal: false },
        ].map(({ id, label, value, onChange, placeholder, decimal }) => (
          <div key={id}>
            <label htmlFor={id} className="block text-sm font-medium text-slate-300 mb-2">{label}</label>
            <input
              id={id} type="text" inputMode={decimal ? 'decimal' : 'numeric'}
              value={value} onChange={onChange}
              className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:ring-2 focus:ring-emerald-500 text-slate-100 font-mono"
              placeholder={placeholder}
            />
            {id === 'ci-rate' && (
              <p className="text-xs text-slate-500 mt-1">
                {language === 'es' ? 'Promedio histórico del mercado: ~7–10% anual' : 'Historical market average: ~7–10% annually'}
              </p>
            )}
          </div>
        ))}

        {/* Toggle timing */}
        <div className="sm:col-span-2">
          <label className="block text-sm font-medium text-slate-300 mb-3">
            {language === 'es' ? 'Momento de la aportación mensual' : 'Monthly contribution timing'}
          </label>
          <div className="relative flex bg-slate-950 border border-slate-800 rounded-xl p-1 gap-1">
            <div
              className={`absolute top-1 bottom-1 w-[calc(50%-6px)] rounded-lg bg-emerald-500 shadow-lg shadow-emerald-900/50 transition-transform duration-200 ease-in-out ${
                contributionTiming === 'end' ? 'translate-x-[calc(100%+4px)]' : 'translate-x-0'
              }`}
            />
            <button
              onClick={() => setContributionTiming('beginning')}
              className={`relative z-10 flex-1 py-2.5 px-4 rounded-lg text-sm font-medium transition-colors duration-200 ${
                contributionTiming === 'beginning' ? 'text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {language === 'es' ? 'Al inicio del mes' : 'At month start'}
            </button>
            <button
              onClick={() => setContributionTiming('end')}
              className={`relative z-10 flex-1 py-2.5 px-4 rounded-lg text-sm font-medium transition-colors duration-200 ${
                contributionTiming === 'end' ? 'text-white' : 'text-slate-400 hover:text-slate-200'
              }`}
            >
              {language === 'es' ? 'Al final del mes' : 'At month end'}
            </button>
          </div>
          <p className="text-xs text-slate-500 mt-2 leading-relaxed">
            {contributionTiming === 'beginning'
              ? (language === 'es'
                  ? 'Anualidad anticipada: cada aporte genera interés desde el primer día del mes.'
                  : 'Annuity due: each contribution earns interest from the first day of the month.')
              : (language === 'es'
                  ? 'Anualidad vencida: modelo estándar. Cada aporte entra al final del mes.'
                  : 'Ordinary annuity: standard model. Each contribution is made at month end.')}
          </p>
        </div>
      </div>

      {/* Resultados */}
      {result && chartData.length > 0 && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-8">
            {[
              { label: language === 'es' ? 'Valor Final'           : 'Final Value',         value: result.finalAmount,    color: 'text-emerald-400' },
              { label: language === 'es' ? 'Total Aportado'        : 'Total Contributed',   value: result.totalInvested,  color: 'text-slate-100'   },
              { label: language === 'es' ? 'Intereses Generados'   : 'Interest Earned',     value: result.totalInterest,  color: 'text-emerald-400' },
            ].map(({ label, value, color }) => (
              <div key={label} className="bg-gradient-to-br from-emerald-950/40 to-slate-800/60 rounded-xl p-4 border border-emerald-800/50 text-center">
                <div className="text-xs text-slate-400 mb-1">{label}</div>
                <div className={`text-2xl font-bold ${color}`}>{symbol}{formatResult(value, currency)}</div>
              </div>
            ))}
          </div>

          {/* Gráfica de área */}
          <div className="bg-slate-800/40 rounded-xl p-4 border border-slate-700 mb-8">
            <h3 className="text-sm font-semibold text-slate-300 mb-4">
              {language === 'es' ? 'Evolución de la inversión' : 'Investment Evolution'}
            </h3>
            <ResponsiveContainer width="100%" height={400}>
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="colorTotal" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%"  stopColor="#10b981" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#10b981" stopOpacity={0}   />
                  </linearGradient>
                  <linearGradient id="colorInvertido" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%"  stopColor="#3b82f6" stopOpacity={0.3} />
                    <stop offset="95%" stopColor="#3b82f6" stopOpacity={0}   />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="#334155" />
                <XAxis dataKey="year" stroke="#64748b" label={{ value: language === 'es' ? 'Años' : 'Years', position: 'bottom', fill: '#64748b' }} />
                <YAxis stroke="#64748b" tickFormatter={(v: number) => `${symbol}${(v / 1000).toFixed(0)}k`} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px' }}
                  formatter={tooltipFormatter}
                  labelFormatter={(label: any) => `${language === 'es' ? 'Año' : 'Year'} ${label}`}
                />
                <Legend />
                <Area type="monotone" dataKey="invertido" name={language === 'es' ? 'Total Aportado' : 'Total Contributed'} stroke="#3b82f6" fill="url(#colorInvertido)" strokeWidth={2} />
                <Area type="monotone" dataKey="total"     name={language === 'es' ? 'Valor Total'    : 'Total Value'}        stroke="#10b981" fill="url(#colorTotal)"    strokeWidth={2} />
              </AreaChart>
            </ResponsiveContainer>
          </div>

          {/* Tabla anual */}
          <div className="bg-slate-800/40 rounded-xl p-4 border border-slate-700 mb-8">
            <h3 className="text-sm font-semibold text-slate-300 mb-4">
              {language === 'es' ? 'Proyección año por año' : 'Year by Year Projection'}
            </h3>
            <div className="overflow-x-auto">
              <table className="w-full text-sm" aria-label={language === 'es' ? 'Proyección anual de inversión' : 'Annual investment projection'}>
                <thead>
                  <tr className="border-b border-slate-700">
                    <th scope="col" className="text-left py-3 px-4 text-slate-400">{language === 'es' ? 'Año' : 'Year'}</th>
                    <th scope="col" className="text-right py-3 px-4 text-slate-400">{language === 'es' ? 'Total Aportado' : 'Total Contributed'}</th>
                    <th scope="col" className="text-right py-3 px-4 text-slate-400">{language === 'es' ? 'Intereses' : 'Interest'}</th>
                    <th scope="col" className="text-right py-3 px-4 text-slate-400">{language === 'es' ? 'Valor Total' : 'Total Value'}</th>
                  </tr>
                </thead>
                <tbody>
                  {annualTable.map((row) => (
                    <tr key={row.year} className="border-b border-slate-800 hover:bg-slate-700/30 transition-colors">
                      <td className="py-3 px-4 font-medium text-slate-200">{row.year}</td>
                      <td className="py-3 px-4 text-right text-slate-300">{symbol}{formatResult(row.aportado,  currency)}</td>
                      <td className="py-3 px-4 text-right text-emerald-400">{symbol}{formatResult(row.intereses, currency)}</td>
                      <td className="py-3 px-4 text-right font-semibold text-slate-100">{symbol}{formatResult(row.total, currency)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          {/* Pie chart */}
          <div className="bg-slate-800/40 rounded-xl p-4 border border-slate-700">
            <h3 className="text-sm font-semibold text-slate-300 mb-4">
              {language === 'es' ? 'Distribución final de la inversión' : 'Final Investment Distribution'}
            </h3>
            <ResponsiveContainer width="100%" height={300}>
              <PieChart>
                <Pie
                  data={[
                    { name: language === 'es' ? 'Total Aportado' : 'Total Contributed', value: result.totalInvested },
                    { name: language === 'es' ? 'Intereses'      : 'Interest',          value: result.totalInterest },
                  ]}
                  cx="50%" cy="50%" labelLine={false}
                  label={({ name, percent }: any) => `${name}: ${((percent as number) * 100).toFixed(0)}%`}
                  outerRadius={80} dataKey="value"
                >
                  <Cell fill="#3b82f6" />
                  <Cell fill="#10b981" />
                </Pie>
                <Tooltip
                  contentStyle={{ backgroundColor: '#1e293b', border: '1px solid #334155', borderRadius: '8px' }}
                  formatter={tooltipFormatter}
                />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </>
      )}
    </div>
  );
}

// ── Página exportada ──────────────────────────────────────────────────────────
export function CalculadoraInversion() {
  const { language } = useLanguage();
  const [globalCurrency, setGlobalCurrency] = useState<Currency>('COP');
  const meta = CURRENCY_MAP[globalCurrency];

  const title =
    language === 'es'
      ? 'Calculadora de Interés Compuesto 2025 | Simulador de Inversión con Aportes Mensuales'
      : 'Compound Interest Calculator 2025 | Investment Simulator with Monthly Contributions';

  const description =
    language === 'es'
      ? 'Proyecta el crecimiento de tu inversión con interés compuesto. Incluye aportaciones mensuales, tabla anual y gráficas de evolución. Calcula el rendimiento de cualquier inversión gratis.'
      : 'Project your investment growth with compound interest. Includes monthly contributions, annual table, and evolution charts. Calculate investment returns for free.';

  const schemaJsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: title,
    applicationCategory: 'FinanceApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description,
    inLanguage: language === 'es' ? 'es' : 'en',
    url: 'https://zentic.app/calculadora-de-inversion',
  });

  return (
    <CurrencyContext.Provider
      value={{ currency: globalCurrency, setCurrency: setGlobalCurrency, symbol: meta?.symbol ?? '$' }}
    >
      <>
        <SEO title={title} description={description} type="SoftwareApplication" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: schemaJsonLd }} />

        <article className="max-w-5xl mx-auto py-6 px-4 sm:px-6" itemScope itemType="https://schema.org/SoftwareApplication">
          <Breadcrumb
            items={[
              { label: language === 'es' ? 'Inicio' : 'Home', href: '/' },
              { label: language === 'es' ? 'Calculadoras' : 'Calculators', href: '/calculators' },
              { label: language === 'es' ? 'Calculadora de Inversión' : 'Investment Calculator' },
            ]}
          />

          <header className="mb-8">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-2 bg-emerald-950/60 rounded-lg border border-emerald-800/50">
                <TrendingUp className="w-6 h-6 text-emerald-400" />
              </div>
              <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">
                {language === 'es' ? 'Capitalización mensual · Gráficas incluidas' : 'Monthly compounding · Charts included'}
              </span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-slate-100 mb-3" itemProp="name">
              {language === 'es' ? 'Calculadora de Interés Compuesto' : 'Compound Interest Calculator'}
            </h1>
            <p className="text-slate-400 text-lg leading-relaxed" itemProp="description">
              {language === 'es'
                ? 'Simula el crecimiento de tu inversión con aportaciones mensuales y visualiza el poder del interés compuesto año por año.'
                : 'Simulate your investment growth with monthly contributions and visualize the power of compound interest year by year.'}
            </p>
          </header>

          <CurrencySelector globalCurrency={globalCurrency} setGlobalCurrency={setGlobalCurrency} language={language} />

          <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl shadow-xl border border-slate-800 p-6 sm:p-8 mb-8">
            <CompoundCalculatorInner />
          </div>

          <section className="mb-8">
            <h2 className="text-xl font-bold text-slate-200 mb-4">
              {language === 'es' ? '¿Por qué usar el interés compuesto?' : 'Why use compound interest?'}
            </h2>
            <p className="text-slate-400 leading-relaxed mb-4">
              {language === 'es'
                ? 'El interés compuesto permite que tu dinero crezca exponencialmente. A diferencia del interés simple, las ganancias generadas se suman al capital y generan nuevas ganancias en los siguientes períodos. Cuanto antes empieces a invertir, mayor será el efecto multiplicador.'
                : 'Compound interest allows your money to grow exponentially. Unlike simple interest, generated earnings are added to the principal and generate new earnings in subsequent periods. The earlier you start investing, the greater the multiplying effect.'}
            </p>
          </section>

          <FaqSection faqs={FAQ_INVERSION} language={language as 'es' | 'en'} />
        </article>
      </>
    </CurrencyContext.Provider>
  );
}