// ─── CalculadoraDeudas.tsx ────────────────────────────────────────────────────
// Ruta: /calculadora-de-deudas
// Calculadora de pago de deudas — SEO 2025
// ─────────────────────────────────────────────────────────────────────────────

import { useState, useEffect } from 'react';
import { CreditCard } from 'lucide-react';
import { useLanguage } from '../../context/LanguageContext';
import { SEO } from '../../components/SEO';
import {
  Currency,
  CurrencyContext,
  CurrencySelector,
  FaqSection,
  Breadcrumb,
  formatResult,
  useFormattedInput,
  useCurrency,
  CURRENCY_MAP,
} from './_shared';

const FAQ_DEUDAS = [
  {
    q_es: '¿Cuánto tiempo tardaré realmente en pagar mi deuda total?',
    q_en: 'How long will it actually take me to pay off my total debt?',
    a_es: 'El tiempo necesario para liquidar una deuda no es una cifra fija, sino el resultado de la interacción entre el capital adeudado, la tasa de interés anual y, sobre todo, la magnitud de tu pago mensual; en términos financieros, cuanto más se acerque tu pago al monto mínimo exigido por el banco, mayor será la proporción que se destine únicamente a cubrir intereses, dejando una fracción mínima para reducir el capital principal, lo que puede extender el plazo de pago durante años; por ello, nuestra calculadora analiza estos factores para ofrecerte un cronograma exacto que te permite visualizar cómo un ligero incremento en tu aportación mensual puede recortar drásticamente el tiempo de vida de la deuda y ahorrarte miles en cargos financieros.',
    a_en: 'The time required to pay off a debt is not a fixed figure but the result of the interaction between the principal owed, the annual interest rate, and, above all, the size of your monthly payment; in financial terms, the closer your payment is to the minimum amount required by the bank, the larger the proportion that will go solely toward covering interest, leaving a minimal fraction to reduce the principal balance, which can extend the repayment term for years; therefore, our calculator analyzes these factors to provide you with an exact timeline, allowing you to visualize how a slight increase in your monthly contribution can drastically cut the debt lifespan and save you thousands in financial charges.',
  },
  {
    q_es: '¿Qué estrategia es mejor para pagar deudas: avalancha o bola de nieve?',
    q_en: 'Which debt payoff strategy is better: avalanche or snowball?',
    a_es: 'La elección entre el método de avalancha y el de bola de nieve depende de si priorizas la eficiencia matemática o la motivación psicológica: el método de avalancha consiste en liquidar primero las deudas con la tasa de interés más alta, lo que técnicamente minimiza el costo total del financiamiento y te permite salir de deudas más rápido; por otro lado, el método de bola de nieve se enfoca en pagar primero los saldos más pequeños para generar victorias rápidas que refuercen tu compromiso emocional, y aunque matemáticamente la avalancha es siempre la opción más óptima para proteger tu patrimonio, muchas personas encuentran éxito en la bola de nieve debido al impulso conductual que genera ver desaparecer cuentas individuales en poco tiempo.',
    a_en: 'Choosing between the avalanche and snowball methods depends on whether you prioritize mathematical efficiency or psychological motivation: the avalanche method involves first paying off debts with the highest interest rates, which technically minimizes the total cost of financing and allows you to get out of debt faster; on the other hand, the snowball method focuses on paying off the smallest balances first to generate quick wins that reinforce your emotional commitment, and while mathematically the avalanche is always the most optimal choice to protect your wealth, many people find success in the snowball method due to the behavioral momentum generated by seeing individual accounts disappear in a short time.',
  },
  {
    q_es: '¿Qué consecuencias tiene pagar solo el mínimo de mi tarjeta de crédito?',
    q_en: 'What are the consequences of paying only the minimum on my credit card?',
    a_es: 'Pagar únicamente el mínimo de una tarjeta de crédito es una de las trampas financieras más costosas, ya que este monto suele cubrir apenas los intereses del mes y una parte insignificante del capital, provocando que la deuda se perpetúe mediante el interés compuesto inverso; bajo este esquema, una deuda de consumo que inicialmente parecía manejable puede terminar costando tres o cuatro veces su valor original y tardar décadas en liquidarse, convirtiéndose en una carga que drena tu flujo de caja mensual y afecta tu puntaje crediticio, por lo que utilizar esta calculadora es vital para entender que cualquier monto pagado por encima del mínimo va directamente a reducir el capital, acelerando la liberación de tu capacidad de endeudamiento.',
    a_en: 'Paying only the minimum on a credit card is one of the most expensive financial traps, as this amount usually barely covers the month\'s interest and an insignificant portion of the principal, causing the debt to perpetuate through reverse compound interest; under this scheme, a consumer debt that initially seemed manageable can end up costing three or four times its original value and take decades to settle, becoming a burden that drains your monthly cash flow and affects your credit score, so using this calculator is vital to understand that any amount paid above the minimum goes directly toward reducing the principal, accelerating the liberation of your borrowing capacity.',
  },
  {
    q_es: '¿Cómo puedo reducir efectivamente el tiempo de pago de mi deuda?',
    q_en: 'How can I effectively reduce the time to pay off my debt?',
    a_es: 'Para reducir el plazo de una deuda de manera efectiva, se deben atacar los intereses mediante tres pilares estratégicos: el incremento de los pagos mensuales recurrentes para atacar el saldo insoluto, la inyección de ingresos extraordinarios —como bonos o devoluciones de impuestos— directamente al capital principal, y la búsqueda de una consolidación o refinanciamiento que reduzca la tasa de interés nominal; incluso un aumento moderado del 10% o 20% en tu pago mensual puede reducir el tiempo de amortización a la mitad en créditos de consumo de alta tasa, transformando el costo financiero total en un ahorro directo que puedes reinvertir para construir tu patrimonio futuro en lugar de financiar las utilidades de la entidad bancaria.',
    a_en: 'To effectively reduce a debt\'s term, you must attack the interest through three strategic pillars: increasing recurring monthly payments to target the outstanding balance, injecting extraordinary income—such as bonuses or tax refunds—directly into the principal capital, and seeking consolidation or refinancing to lower the nominal interest rate; even a moderate 10% or 20% increase in your monthly payment can cut the amortization time in half for high-rate consumer loans, transforming the total financial cost into direct savings that you can reinvest to build your future wealth instead of financing the banking institution\'s profits.',
  },
  {
    q_es: '¿Cómo afecta el nivel de deuda a mi puntaje crediticio o buró?',
    q_en: 'How does my debt level affect my credit score?',
    a_es: 'El nivel de utilización de tu crédito es uno de los factores más influyentes en tu puntaje crediticio, representando aproximadamente el 30% del cálculo total; este indicador mide qué proporción de tus límites de crédito estás utilizando actualmente, por lo que mantener saldos cercanos al límite en tus tarjetas de crédito puede interpretarse como una señal de riesgo financiero y reducir tu calificación, incluso si realizas tus pagos a tiempo; reducir tus deudas mediante las estrategias proyectadas en esta calculadora no solo te ahorra intereses, sino que mejora significativamente tu perfil ante las instituciones financieras, permitiéndote acceder a mejores tasas y mayores líneas de crédito en el futuro.',
    a_en: 'Your credit utilization ratio is one of the most influential factors in your credit score, representing approximately 30% of the total calculation; this indicator measures what proportion of your credit limits you are currently using, so keeping balances close to the limit on your credit cards can be interpreted as a sign of financial risk and lower your rating, even if you make your payments on time; reducing your debts through the strategies projected in this calculator not only saves you interest but significantly improves your profile with financial institutions, allowing you to access better rates and larger credit lines in the future.',
  },
  {
    q_es: '¿Es conveniente pedir un préstamo para pagar mis deudas actuales?',
    q_en: 'Is it wise to take out a loan to pay off my current debts?',
    a_es: 'La consolidación de deuda mediante un nuevo préstamo es una estrategia inteligente solo si se cumplen dos condiciones fundamentales: que la tasa de interés del nuevo crédito sea significativamente inferior a la tasa promedio de tus deudas actuales y que mantengas la disciplina de no volver a utilizar las líneas de crédito que queden liberadas; al unificar varias cuentas con intereses altos (como tarjetas de crédito) en un solo pago mensual con una tasa menor, puedes reducir el costo financiero total y simplificar tu administración mensual, pero es vital utilizar una calculadora de deuda para comparar el costo total a pagar al final del plazo y asegurar que la consolidación realmente represente un beneficio económico y no solo una extensión del tiempo de endeudamiento.',
    a_en: 'Debt consolidation through a new loan is a smart strategy only if two fundamental conditions are met: the interest rate of the new credit must be significantly lower than the average rate of your current debts, and you must maintain the discipline not to reuse the credit lines that are freed up; by unifying several high-interest accounts (such as credit cards) into a single monthly payment with a lower rate, you can reduce the total financial cost and simplify your monthly management, but it is vital to use a debt calculator to compare the total cost to be paid at the end of the term and ensure that consolidation truly represents an economic benefit and not just an extension of the debt duration.',
  },
];

function DebtCalculatorInner() {
  const { symbol, currency } = useCurrency();
  const { language } = useLanguage();
  const { value: debtValue,    rawValue: debtAmount,     handleChange: setDebtAmount     } = useFormattedInput('0', false);
  const { value: rateValue,    rawValue: interestRate,   handleChange: setInterestRate   } = useFormattedInput('0', true);
  const { value: paymentValue, rawValue: monthlyPayment, handleChange: setMonthlyPayment } = useFormattedInput('0', false);
  const [result, setResult] = useState<{
    monthsToPay: number;
    totalInterest: number;
    totalPaid: number;
    payoffDate: string;
    strategy: string;
  } | null>(null);

  useEffect(() => { calculate(); }, [debtAmount, interestRate, monthlyPayment]);

  const calculate = () => {
    const debt        = debtAmount;
    const annualRate  = interestRate / 100;
    const monthly     = monthlyPayment;
    const monthlyRate = annualRate / 12;
    let balance       = debt;
    let months        = 0;
    let totalInterest = 0;

    while (balance > 0 && months < 600) {
      const interest       = balance * monthlyRate;
      totalInterest       += interest;
      let principalPayment = monthly - interest;
      if (principalPayment <= 0) {
        setResult({
          monthsToPay: Infinity, totalInterest: 0, totalPaid: 0, payoffDate: language === 'es' ? 'Nunca' : 'Never',
          strategy: language === 'es'
            ? `Tu pago mensual no cubre los intereses. Necesitas pagar al menos ${symbol}${formatResult(balance * monthlyRate + 1, currency)} mensuales.`
            : `Your monthly payment does not cover the interest. You need to pay at least ${symbol}${formatResult(balance * monthlyRate + 1, currency)} monthly.`,
        });
        return;
      }
      if (principalPayment > balance) principalPayment = balance;
      balance -= principalPayment;
      months++;
    }

    const totalPaid = debt + totalInterest;
    const today = new Date();
    const payoffDate = new Date(today.setMonth(today.getMonth() + months));
    let strategy = '';
    if (months <= 12) {
      strategy = language === 'es' ? 'Pagarás tu deuda en menos de un año. ¡Excelente plan!' : 'You will pay off your debt in less than a year. Excellent plan!';
    } else if (months <= 24) {
      strategy = language === 'es' ? 'Buen plan. Considera aumentar tus pagos mensuales para ahorrar en intereses.' : 'Good plan. Consider increasing your monthly payments to save on interest.';
    } else {
      strategy = language === 'es'
        ? `Si aumentas tu pago mensual en ${symbol}${formatResult(monthly * 0.2, currency)}, pagarías más rápido y ahorrarías en intereses.`
        : `If you increase your monthly payment by ${symbol}${formatResult(monthly * 0.2, currency)}, you will pay off faster and save on interest.`;
    }
    setResult({
      monthsToPay: months, totalInterest, totalPaid,
      payoffDate: payoffDate.toLocaleDateString(language === 'es' ? 'es-ES' : 'en-US'),
      strategy,
    });
  };

  return (
    <div className="max-w-2xl mx-auto">
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-6 mb-6">
        <div>
          <label htmlFor="debt-amount" className="block text-sm font-medium text-slate-300 mb-2">
            {language === 'es' ? 'Monto de la Deuda' : 'Debt Amount'}
          </label>
          <input id="debt-amount" type="text" inputMode="numeric" value={debtValue} onChange={setDebtAmount}
            className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:ring-2 focus:ring-emerald-500 text-slate-100 font-mono"
            placeholder="10.000" />
        </div>
        <div>
          <label htmlFor="debt-rate" className="block text-sm font-medium text-slate-300 mb-2">
            {language === 'es' ? 'Tasa de Interés Anual (%)' : 'Annual Interest Rate (%)'}
          </label>
          <input id="debt-rate" type="text" inputMode="decimal" value={rateValue} onChange={setInterestRate}
            className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:ring-2 focus:ring-emerald-500 text-slate-100 font-mono"
            placeholder="24" />
        </div>
        <div className="sm:col-span-2">
          <label htmlFor="debt-payment" className="block text-sm font-medium text-slate-300 mb-2">
            {language === 'es' ? 'Pago Mensual' : 'Monthly Payment'}
          </label>
          <input id="debt-payment" type="text" inputMode="numeric" value={paymentValue} onChange={setMonthlyPayment}
            className="w-full px-4 py-3 bg-slate-800 border border-slate-700 rounded-lg focus:ring-2 focus:ring-emerald-500 text-slate-100 font-mono"
            placeholder="500" />
        </div>
      </div>

      {result && (
        <div className="space-y-4" aria-live="polite">
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
            <div className="bg-gradient-to-br from-emerald-950/40 to-slate-800/60 rounded-xl p-4 border border-emerald-800/50 text-center">
              <div className="text-xs text-slate-400 mb-1">{language === 'es' ? 'Tiempo de pago' : 'Payoff Time'}</div>
              <div className="text-2xl font-bold text-emerald-400">
                {result.monthsToPay === Infinity ? '∞' : `${result.monthsToPay} ${language === 'es' ? 'meses' : 'months'}`}
              </div>
            </div>
            <div className="bg-gradient-to-br from-emerald-950/40 to-slate-800/60 rounded-xl p-4 border border-emerald-800/50 text-center">
              <div className="text-xs text-slate-400 mb-1">{language === 'es' ? 'Total a Pagar' : 'Total to Pay'}</div>
              <div className="text-xl font-bold text-slate-100">{symbol}{formatResult(result.totalPaid, currency)}</div>
            </div>
            <div className="bg-gradient-to-br from-emerald-950/40 to-slate-800/60 rounded-xl p-4 border border-emerald-800/50 text-center">
              <div className="text-xs text-slate-400 mb-1">{language === 'es' ? 'Total Intereses' : 'Total Interest'}</div>
              <div className="text-xl font-bold text-rose-400">{symbol}{formatResult(result.totalInterest, currency)}</div>
            </div>
          </div>
          <div className="bg-amber-950/40 rounded-xl p-5 border border-amber-800/50">
            <h3 className="text-sm font-semibold mb-3 text-amber-400">{language === 'es' ? 'Recomendación' : 'Recommendation'}</h3>
            <p className="text-sm text-slate-300">{result.strategy}</p>
            {result.monthsToPay !== Infinity && (
              <p className="text-xs text-slate-400 mt-3">
                {language === 'es' ? 'Fecha estimada de pago' : 'Estimated payoff date'}: {result.payoffDate}
              </p>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export function CalculadoraDeudas() {
  const { language } = useLanguage();
  const [globalCurrency, setGlobalCurrency] = useState<Currency>('COP');
  const meta = CURRENCY_MAP[globalCurrency];

  const title =
    language === 'es'
      ? 'Calculadora de Pago de Deudas 2025 | ¿Cuándo terminaré de pagar mi deuda?'
      : 'Debt Payoff Calculator 2025 | When Will I Pay Off My Debt?';

  const description =
    language === 'es'
      ? 'Descubre en cuántos meses pagarás tu deuda y cuánto pagarás en intereses. Estrategias para reducir el plazo de tu tarjeta de crédito o préstamo. Gratis.'
      : 'Discover how many months it will take to pay off your debt and how much interest you will pay. Strategies to reduce your credit card or loan term. Free.';

  const schemaJsonLd = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: title,
    applicationCategory: 'FinanceApplication',
    operatingSystem: 'Web',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    description,
    inLanguage: language === 'es' ? 'es' : 'en',
    url: 'https://zentic.app/calculadora-de-deudas',
  });

  return (
    <CurrencyContext.Provider value={{ currency: globalCurrency, setCurrency: setGlobalCurrency, symbol: meta?.symbol ?? '$' }}>
      <>
        <SEO title={title} description={description} type="SoftwareApplication" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: schemaJsonLd }} />

        <article className="max-w-3xl mx-auto py-6 px-4 sm:px-6" itemScope itemType="https://schema.org/SoftwareApplication">
          <Breadcrumb
            items={[
              { label: language === 'es' ? 'Inicio' : 'Home', href: '/' },
              { label: language === 'es' ? 'Calculadoras' : 'Calculators', href: '/calculators' },
              { label: language === 'es' ? 'Calculadora de Deudas' : 'Debt Payoff Calculator' },
            ]}
          />

          <header className="mb-8">
            <div className="flex items-center gap-3 mb-3">
              <div className="p-2 bg-emerald-950/60 rounded-lg border border-emerald-800/50">
                <CreditCard className="w-6 h-6 text-emerald-400" />
              </div>
              <span className="text-xs font-semibold text-emerald-400 uppercase tracking-wider">
                {language === 'es' ? 'Tarjetas · Préstamos · Hipotecas' : 'Credit cards · Loans · Mortgages'}
              </span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-bold text-slate-100 mb-3" itemProp="name">
              {language === 'es' ? 'Calculadora de Pago de Deudas' : 'Debt Payoff Calculator'}
            </h1>
            <p className="text-slate-400 text-lg leading-relaxed" itemProp="description">
              {language === 'es'
                ? 'Calcula cuánto tiempo tardarás en quedar libre de deudas y cuánto pagarás en intereses según tu cuota mensual.'
                : 'Calculate how long it will take to become debt-free and how much you will pay in interest based on your monthly payment.'}
            </p>
          </header>

          <CurrencySelector globalCurrency={globalCurrency} setGlobalCurrency={setGlobalCurrency} language={language} />

          <div className="bg-slate-900/60 backdrop-blur-sm rounded-2xl shadow-xl border border-slate-800 p-6 sm:p-8 mb-8">
            <DebtCalculatorInner />
          </div>

          <FaqSection faqs={FAQ_DEUDAS} language={language as 'es' | 'en'} />
        </article>
      </>
    </CurrencyContext.Provider>
  );
}